# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "stepanovns/centos8-Minimal" 

    config.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 2
    end
   
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end

    boxes = [
          { :name => "dynweb",
            :ip => "192.168.57.10",
          },
        ]

     boxes.each do |opts|
       config.vm.define opts[:name] do |config|
       config.vm.hostname = opts[:name]
       config.vm.network "private_network", ip: opts[:ip]
     if config.vm.hostname == "dynweb"
       config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/provision.yml"
        ansible.host_key_checking = "False"
        ansible.limit = "all"
       end
     end  
       end
     end

    config.vm.define "dynweb" do |web|
        web.vm.network "forwarded_port", guest:8081, host:8081
        web.vm.network "forwarded_port", guest:8082, host:8082
        web.vm.network "forwarded_port", guest:8083, host:8083
    end



end
