# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = 'stepanovns/centos8-Minimal'
  if Vagrant.has_plugin?("vagrant-vbguest")
	config.vbguest.auto_update = false
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
	v.check_guest_additions = false
  end

  # Define two VMs with static private IP addresses.
  boxes = [
    {
	  :name => "centralServer",
      :ip => "192.168.50.10",
    },
    {
	  :name => "inetRouter2",
      :ip => "192.168.50.15",
    },
    {
	  :name => "inetRouter",
      :ip => "192.168.50.20",
    }
  ]
  
  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]

    end
  end

	config.vm.define "inetRouter2" do |web| 
		web.vm.network "forwarded_port", guest:8080, host:8080
	end



end
