---
- name: Project
  hosts: all
  become: yes
  tasks:

  - name: Change dnf repository vault on
    ansible.builtin.shell:
      cmd: sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

  - name: Change dnf repository mirrorlist off
    ansible.builtin.shell:
      cmd: sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*

  - name: install base tools
    ansible.builtin.dnf:
      name:
        - vim
        - telnet
        - glibc-langpack-ru
        - git
      state: present
      update_cache: true

  - name: install locale
    ansible.builtin.shell:
      cmd: localectl set-locale LANG=ru_RU.UTF8

  - name: Copy hosts
    ansible.builtin.copy:
      src: files/hosts
      dest: /etc/hosts
      mode: '0644'

  - name: Install Zabbix agent
    ansible.builtin.shell:
      cmd: rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm && dnf -y install zabbix-agent
    ignore_errors: true

  - name: install timezone
    ansible.builtin.shell:
      cmd: timedatectl set-timezone Europe/Moscow 

  - name: copy zabbix-agent config
    ansible.builtin.copy:
      src: files/zabbix_agentd.conf
      dest: /etc/zabbix/zabbix_agentd.conf
      mode: '0644'

  - name: Start zabbix agent service
    ansible.builtin.systemd:
      name: zabbix-agent
      state: started
      enabled: true

- name: DbHost
  hosts: db
  become: yes
  roles:
  - db

- name: ProxyHost
  hosts: proxy
  become: yes
  roles:
  - proxy

- name: WordpressHost
  hosts: wordpress
  become: yes
  roles:
  - wordpress

- name: ZabbixHost
  hosts: zabbix
  become: yes
  roles:
  - zabbix
