---
- name: Project
  hosts: server
  become: yes
  tasks:

  - name: Change dnf repository vault on
    ansible.builtin.shell:
      cmd: sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

  - name: Change dnf repository mirrorlist off
    ansible.builtin.shell:
      cmd: sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*

  - name: install base tools
    dnf:
      name:
        - vim
        - telnet
        - glibc-langpack-ru
        - git
      state: present
      update_cache: true

  - name: install locale
    shell:
      cmd: localectl set-locale LANG=ru_RU.UTF8

  - name: Install Zabbxi agent
    shell: 
      cmd: rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm && dnf -y install zabbix-agent
    ignore_errors: true

  - name: install timezone
    shell:
      cmd: timedatectl set-timezone Europe/Moscow 

- name: Test
  hosts: server
  become: yes
  roles:
    - firewall
