# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "stepanovns/centos8-Minimal"
	if Vagrant.has_plugin?("vagrant-vbguest")
		config.vbguest.auto_update = false
	end
end
