# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :server => {
        :box_name => "stepanovns/centos8-Minimal",
        :vm_name => "server",
        :net => [
                   {ip: '192.168.50.10', adapter: 2, netmask: "255.255.255.0"},
                ]
  },

  :client => {
        :box_name => "stepanovns/centos8-Minimal",
        :vm_name => "client",
        :net => [
                   {ip: '192.168.50.11', adapter: 2, netmask: "255.255.255.0", },
                ]
  },

  }


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      if Vagrant.has_plugin?("vagrant-vbguest")
        box.vbguest.auto_update = false
      end


          if boxconfig[:vm_name] == "client"
           box.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.inventory_path = "hosts"
            ansible.host_key_checking = "False"
            ansible.limit = "all"
           end
      end

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ip: ipconf[:ip], adapter: ipconf[:adapter], netmask: ipconf[:netmask], virtualbox__intnet: ipconf[:virtualbox__intnet] 
      end

     end
  end
end
