---
- name: install base tools
  dnf:
    name:
      - python3-pexpect.noarch
      - python3-psycopg2
    state: present
    update_cache: true


- name: Create replicator user
  become_user: postgres
  postgresql_user:
    name: replicator
    password: '{{ replicator_password }}'
    role_attr_flags: REPLICATION 
  ignore_errors: true
  when: (ansible_hostname == "master")


- name: stop postgresql-server on slave
  service: 
    name: postgresql-14
    state: stopped
  when: (ansible_hostname == "slave")


- name: copy postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/14/data/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0600'
  when: (ansible_hostname == "master")


- name: copy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/14/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'
  when: (ansible_hostname == "master")
 
- name: restart postgresql-server on master
  service: 
    name: postgresql-14
    state: restarted
  when: (ansible_hostname == "master")


- name: Remove files from data catalog
  file:
    path: /var/lib/pgsql/14/data/
    state: absent
  when: (ansible_hostname == "slave")


- name: copy files from master to slave
  become_user: postgres
  expect:
    command: 'pg_basebackup -h {{ master_ip }} -U  replicator -p 5432 -D /var/lib/pgsql/14/data/ -R -P'
    responses: 
      '.*Пароль*': "{{ replicator_password }}"
  when: (ansible_hostname == "slave")


- name: copy postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/14/data/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0600'
  when: (ansible_hostname == "slave")


- name: copy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/14/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'
  when: (ansible_hostname == "slave")
 

- name: start postgresql-server on slave
  service: 
    name: postgresql-14
    state: started
  when: (ansible_hostname == "slave")
