---
# tasks file for zabbix
#- name: downloads zabbix-server
#  ansible.builtin.shell:
#    cmd: rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm
#  ignore_errors: yes

    
- name: Installing Remi Repository
  ansible.builtin.shell:
    cmd: dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
  ignore_errors: true

- name: Reset php
  ansible.builtin.shell:
    cmd: dnf -y module reset php
    
- name: Install php remi
  ansible.builtin.shell:
    cmd: dnf -y module install php:remi-7.4

- name: Installing php
  ansible.builtin.dnf:
    enablerepo: "rem,rem-php74"
    name:
      - php
      - php-common
      - php-cli
      - php-gd
      - php-mysqlnd
      - php-fpm
    state: latest

- name: Install zabbix-server 
  ansible.builtin.dnf:
    name:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-selinux-policy
      - zabbix-agent
    state: latest

- name: Set httpd_can_network_connect flag on
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Set httpd_graceful_shutdown flag on
  ansible.posix.seboolean:
    name: httpd_graceful_shutdown 
    state: true
    persistent: true

- name: Set httpd_can_network_connect_db flag on
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true

- name: Copy Config Zabbix-server
  ansible.builtin.copy:
    src: files/zabbix/zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    mode: '0644'

- name: Start httpd
  ansible.builtin.systemd:
    state: started 
    name: httpd
    enabled: true

- name: Start Zabbix-server
  ansible.builtin.systemd:
    state: started
    name: zabbix-server
    enabled: true
