Vagrant.configure("2") do |config|
	config.vm.box = "stepanovns/centos8-Minimal"
	if Vagrant.has_plugin?("vagrant-vbguest")
		config.vbguest.auto_update = false
	end
	config.vm.provider "virtualbox" do |v| 
		v.memory = 512
		v.cpus = 1 
		v.customize ["modifyvm", :id, "--vram", "16"]
	end 
	config.vm.provision "shell", path: "first.sh"
	config.vm.provision "shell", path: "second.sh"
	config.vm.provision "shell", path: "third.sh"
end
