# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "stepanovns/centos8-Minimal",
    :vm_name => "inetRouter",
    :net => [
      { adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
      { adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
      {ip: '192.168.56.20', adapter: 8},
  ]
},
:centralRouter => {
  :box_name => "stepanovns/centos8-Minimal",
  :vm_name => "centralRouter",
  :net => [
             {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
             {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
             {ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
             {ip: '192.168.56.11', adapter: 8},
          ]
},


:testClient1 => {
  :box_name => "stepanovns/centos8-Minimal",
  :vm_name => "testClient1",
  :net => [
      {adapter: 2, auto_config: false, virtualbox__intnet: "testvlan"},
      {ip: '192.168.56.21', adapter: 8},
 ]
},

:testServer1 => {
  :box_name => "stepanovns/centos8-Minimal",
  :vm_name => "testServer1",
  :net => [
      {adapter: 2, auto_config: false, virtualbox__intnet: "testvlan"},
      {ip: '192.168.56.22', adapter: 8},
]
},

:testClient2 => {
  :box_name => "stepanovns/centos8-Minimal",
  :vm_name => "testClient2",
  :net => [
      {adapter: 2, auto_config: false, virtualbox__intnet: "testvlan"},
      {ip: '192.168.56.31', adapter: 8},
 ]
},

:testServer2 => {
  :box_name => "stepanovns/centos8-Minimal",
  :vm_name => "testServer2",
  :net => [
      {adapter: 2, auto_config: false, virtualbox__intnet: "testvlan"},
      {ip: '192.168.56.32', adapter: 8},
 ]
},

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      if Vagrant.has_plugin?("vagrant-vbguest")
        box.vbguest.auto_update = false
      end

     if boxconfig[:vm_name] == "testServer2"
       box.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "hosts"
        ansible.host_key_checking = "False"
        ansible.limit = "all"
       end
     end  

      

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ip: ipconf[:ip], adapter: ipconf[:adapter], netmask: ipconf[:netmask], virtualbox__intnet: ipconf[:virtualbox__intnet] 
      end

     end
  end
end
