# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

config.vm.define "pxeserver" do |server|
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  config.vm.synced_folder ".", "/vagrant", disabled: false
  server.vm.box = 'stepanovns/centos8-Minimal'
#  server.vm.disk :disk, size: "15GB", name: "extra_storage1"

  server.vm.host_name = 'pxeserver'
  server.vm.network :private_network, 
                     ip: "10.0.0.20", 
                     virtualbox__intnet: 'pxenet'

   server.vm.network "forwarded_port", guest: 80, host: 8081

  server.vm.provider "virtualbox" do |vb|
      disk = './disk.vdi'
      needsController = false
      unless File.exist?(disk)
       vb.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', 30 * 1024]
         needsController = true
      end
        if needsController == true
            #vb.customize ["storagectl", :id, "--name", "SataController", "--add", "sata" ]
            vb.customize ['storageattach', :id,  '--storagectl', 'SataController', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', disk]
       end
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  server.vm.provision "shell", inline: <<-SHELL
   pvcreate /dev/sdb
   vgextend cs_otus-1 /dev/sdb
   lvextend -r -l +100%FREE /dev/cs_otus-1/root
   SHELL
  # ENABLE to setup PXE
  server.vm.provision "shell",
#    name: "Setup PXE server",
    path: "pxe_setup.sh"
end
# config used from this
# https://github.com/eoli3n/vagrant-pxe/blob/master/client/Vagrantfile
  config.vm.define "pxeclient" do |pxeclient|
    pxeclient.vm.box = 'stepanovns/centos8-Minimal'
    pxeclient.vm.host_name = 'pxeclient'
    pxeclient.vm.network :private_network, ip: "10.0.0.21", virtualbox_intnet: "pxenet"
    pxeclient.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
      vb.customize ["modifyvm", :id, "--vram", "20"]
      vb.customize [
          'modifyvm', :id,
          '--nic1', 'intnet',
          '--intnet1', 'pxenet',
          '--nic2', 'nat',
          '--boot1', 'net',
          '--boot2', 'none',
          '--boot3', 'none',
          '--boot4', 'none'
        ]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end
  end
end
