---
- name: MySql
  hosts: all
  become: yes
  tasks:

  - name: install base tools
    dnf:
      name:
        - vim
        - telnet
        - glibc-langpack-ru
      state: present
      update_cache: true

  - name: install locale
    shell:
      cmd: localectl set-locale LANG=ru_RU.UTF8

  - name: install timezone
    shell:
      cmd: timedatectl set-timezone Europe/Moscow 

  - name: install repo
    shell: dnf -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm

  - name: disable old mysql module 
    shell: dnf -y  module disable mysql

  - name: Enable the Percona Server 5.7
    shell: percona-release setup ps57

  - name: install Percona-Server
    dnf:
      name:
        - Percona-Server-server-57

  - name: Copy file with owner and permissions
    copy:
      src: '{{ item }}'
      dest: /etc/my.cnf.d/
      owner: root
      group: root
      mode: '0644'
    loop:
      - files/base.cnf
      - files/binlog.cnf
      - files/max-connections.cnf
      - files/perfomance.cnf
      - files/slow-query.cnf


- hosts: master
  become: yes
  tasks: 
  - name: Copy bet.dmp
    copy:
      src: files/bet.dmp
      dest: /home/vagrant/bet.dmp
      owner: root
      group: root
      mode: '0644'

  - name: start mysql service
    service:
      name: mysql
      state: started

  - name: Execute script
    script: files/master.sh

  - name: Fetch MysqlDUMP
    fetch:
      src: /home/vagrant/master.sql
      dest: ./files/master.sql
      flat: yes

- hosts: slave
  become: yes
  tasks: 
  - name: Change binlog config
    lineinfile:
      path: /etc/my.cnf.d/binlog.cnf
      regexp: '^#replicate-ignore-table=bet.events_on_demand' 
      line: 'replicate-ignore-table=bet.events_on_demand'

  - name: Change binlog config
    lineinfile:
      path: /etc/my.cnf.d/binlog.cnf
      regexp: '#replicate-ignore-table=bet.v_same_event'
      line: 'replicate-ignore-table=bet.v_same_event'

  - name: Change base config
    lineinfile:
      path: /etc/my.cnf.d/base.cnf
      regexp: '^server-id'
      line: 'server-id = 2'

  - name: Transfer MysqlDUMP
    copy:
      src: ./files/master.sql
      dest: /home/vagrant/master.sql

  - name: start mysql service
    service:
      name: mysql
      state: started
  
  - name: Execute script
    script: files/slave.sh

- hosts: master
  become: yes
  tasks:
  - name: replication
    shell:
      cmd: mysql -e "RESET MASTER"

- hosts: slave
  become: yes
  tasks: 
  - name: restart replication
    shell:
      cmd: mysql -e "STOP SLAVE; RESET SLAVE; RESET MASTER; START SLAVE"
