# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"

    config.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 1
    end
   
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end

    boxes = [
          { :name => "ipa.otus.lan",
            :ip => "192.168.57.10",
          },
          { :name => "client1.otus.lan",
            :ip => "192.168.57.11",
          },
          { :name => "client2.otus.lan",
            :ip => "192.168.57.12",
          }
        ]

     boxes.each do |opts|
       config.vm.define opts[:name] do |config|
       config.vm.hostname = opts[:name]
       config.vm.network "private_network", ip: opts[:ip]
     if config.vm.hostname == "client2.otus.lan"
       config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "hosts"
        ansible.host_key_checking = "False"
        ansible.limit = "all"
       end
     end  
       end
     end

    config.vm.define "ipa.otus.lan" do |web|
        web.vm.network "forwarded_port", guest:80, host:8080
    end



end
