---
- hosts: web
  become: true
  tasks:
  - name: install epel-release
    yum:
      name: epel-release
      state: present
  - name: install nginx
    yum:
      name: nginx
      state: present

  - name: copy nginx.conf
    copy:
      src: ./provision/web/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'

  - name: copy index.hmtl
    copy:
      src: ./provision/web/index.html
      dest: /usr/share/doc/HTML/index.html
      owner: root
      group: root
      mode: '0755'

  - name: restart nginx
    ansible.builtin.service:
      name: nginx.service
      state: reloaded
       
- hosts: log 
  become: true
  tasks:
  - name: copy rsyslog.conf
    copy:
      src: ./provision/log/rsyslog.conf
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: '0644'

  - name: restart rsyslog
    ansible.builtin.service:
      name: rsyslog.service
      state: restarted

- hosts: clog 
  become: true
  tasks:
  - name: copy rsyslog.conf
    copy:
      src: ./provision/clog/rsyslog.conf
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: '0644'

  - name: restart rsyslog
    ansible.builtin.service:
      name: rsyslog.service
      state: restarted
