# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
  if Vagrant.has_plugin?("vagrant-vbguest")
	config.vbguest.auto_update = false
  end


  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
	v.check_guest_additions = false
  end

  # Define two VMs with static private IP addresses.
  boxes = [
    {
	  :name => "web",
      :ip => "192.168.50.10",
    },
    {
	  :name => "log",
      :ip => "192.168.50.15",
    },
    {
	  :name => "clog",
      :ip => "192.168.50.20",
    }
  ]
  
  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]

    end
  end

	config.vm.define "web" do |web| 
		web.vm.network "forwarded_port", guest:80, host:8033
	end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end


#	config.vm.define "elk" do |elk|
#	  elk.vm.box = "centos/7" 
#	  elk.vm.box_version = "2004.01"
#	  elk.vm.hostname = 'elk'
#
#	  elk.vm.network :private_network, ip: "192.168.50.20"
#	  elk.vm.network "forwarded_port", guest:5601, host:5601
#
#	  if Vagrant.has_plugin?("vagrant-vbguest")
#		config.vbguest.auto_update = false
#	  end
#
#	  elk.vm.provider :virtualbox do |v|
#			v.customize ["modifyvm", :id, "--memory", "4096"] 
#			v.customize ["modifyvm", :id, "--name", "elk"]
#			v.customize ["modifyvm", :id, "--cpus", "2"]
#		end
#	end

end

