# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "stepanovns/centos8-Minimal" 

    config.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 1
    end
   
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end

    boxes = [
          { :name => "master",
            :ip => "192.168.57.10",
          },
          { :name => "slave",
            :ip => "192.168.57.11",
          },
          { :name => "barman",
            :ip => "192.168.57.12",
          }
        ]

     boxes.each do |opts|
       config.vm.define opts[:name] do |config|
       config.vm.hostname = opts[:name]
       config.vm.network "private_network", ip: opts[:ip]
     if config.vm.hostname == "barman"
       config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/provision.yml"
        ansible.inventory_path = "ansible/hosts"
        ansible.host_key_checking = "False"
        ansible.limit = "all"
       end
     end  
       end
     end

#    config.vm.define "ipa.otus.lan" do |web|
#        web.vm.network "forwarded_port", guest:80, host:8080
#    end



end
