# Описание параметров ВМ
MACHINES = {
  # Имя DV "pam"
  :"pam" => {
              # VM box
#              :box_name => "centos/stream8",
              :box_name => "stepanovns/centos8-Minimal", 
              #box_version
#              :box_version => "20210210.0",
              # Количество ядер CPU
              :cpus => 2,
              # Указываем количество ОЗУ (В Мегабайтах)
              :memory => 1024,
              # Указываем IP-адрес для ВМ
              :ip => "192.168.57.15",
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
     if Vagrant.has_plugin?("vagrant-vbguest")
         config.vbguest.auto_update = false
     end
    # Отключаем сетевую папку
    config.vm.synced_folder ".", "/vagrant", disabled: true

	config.vm.provision "ansible" do |ansible|
	#	ansible.verbose="vvv"	
    	ansible.playbook = "provision/playbook.yml"
        ansible.become = "true"
    end
    
    # Добавляем сетевой интерфейс
    config.vm.network "private_network", ip: boxconfig[:ip]
    # Применяем параметры, указанные выше
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
    #	v.customize ["modifyvm", :id, "--spec-ctrl", "on"]
      end
      box.vm.provision "shell", inline: <<-SHELL
          #Разрешаем подключение пользователей по SSH с использованием пароля
          sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
          #Перезапуск службы SSHD
          systemctl restart sshd.service
  	  SHELL
    end
  end
end

